# Stylua configuration for Locustron project

indent_type = "Spaces"
indent_width = 3
column_width = 120
line_endings = "Unix"
quote_style = "ForceDouble"
call_parentheses = "Input"
collapse_simple_statement = "Always"

[sort_requires]
enabled = false